### ISSUE TITLE
keyboard controls?

### ISSUE THREAD

**Issue by gilescope** [zdcthomas/dmux#13]
On the whole the UI discoverability is great - those right click menus work a treat.
(I was looking for 'Paste Xyz' but 'Type Xyz' works well.)

I'm guessing there's a global modifier key that allows you to split a window? C-m h or something? - I couldn't find much in the docs or help about which keystrokes to use...

**Comment by zdcthomas** [comment]
I’m not sure what right click menu you’re talking about? Dmux is only a abstraction on top of tmux that allows you reuse profiles for opening tmux windows, and it sounds like the behavior your talking about is coming from your terminal emulator + tmux itself. If it’s tmux you need help with, I’d look here https://www.man7.org/linux/man-pages/man1/tmux.1.html
Let me know if I’m missing something

**Comment by gilescope** [comment]
Ah I didn’t realise tmux was still under the hood. We can close this then - I can just configure in .tmux.config

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zdcthomas** [comment]
gotcha, I might try to make that more clear in the readme
