### ISSUE TITLE
Panics if tmux not installed

### ISSUE THREAD

**Issue by My-** [zdcthomas/dmux#17]
Hi,
Then I tested `dmux` I had no `tmux` installed. When I run `dmux ./` it panicked with a not very useful message. After installing tmux all worked. 
I believe to add more useful message would be good as seeing panic doesn't look very nice.

It just a suggestion. 

In case it matters:
- my machine is Linux Mint 20
- installed `dmux` using `cargo install`
- cargo 1.45.0 (744bd1fbb 2020-06-15)

PS. I don't have panic output as after installing `tmux` it went away.

**Comment by zdcthomas** [comment]
Ok, this should return a better error message now. If it doesn't definitely open another issue. Thanks for the feedback and the patience!
